[package]
name = "Advent-of-Code-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
grid = "0.15.0"
itertools = "0.13.0"
lazy_static = "1.5.0"
nalgebra = "0.33.2"
num = "0.4.3"
pathfinding = "4.12.0"
rayon = "1.10.0"
regex = "1.11.1"
